### ISSUE TITLE
Use AppCompat or Material

### ISSUE THREAD

**Issue by pedromassango** [franticnick/cointrends#1]
We should not use material design and appCompat at the same time. Remove appCompat and use only material.

**Comment by franticnick** [comment]
> We should not use material design and appCompat at the same time. Remove appCompat and use only material.

I guess you thought on "com.google.android.material:material:1.1.0-alpha01" dependency. It is ok to use it as it's listed in the migration guide for androidx (in the list, migration from "com.android.support:design" artifact)

Check here: https://developer.android.com/jetpack/androidx/migrate

But, project actually doesn't need it. So, it's removed now :)
